### ISSUE TITLE
Transferring database from Tribler Stable to Experimental

### ISSUE THREAD

**Issue by Coldblackice** [qstokkink/TriblerExperimental#31]
Is it possible to transfer the database from Tribler Stable to Experimental? I had a number of torrents seeding and unfinished torrents, which I assumed would carry over to Experimental, however, Experimental is empty.

Also, Experimental's search (box) isn't working, either.

**Comment by qstokkink** [comment]
It _should_ be a matter of copying the contents of your `dlcheckpoints` and `sqlite` directories of the version in the `.Tribler` directory you're migrating into your `.TriblerExperimental` directory. You can find those directories in your home directory on UNIX/Mac or inside `%APPDATA%` on Windows.

For example, for my setup, I would copy `/home/quinten/.Tribler/7.14/dlcheckpoints` to `/home/quinten/.TriblerExperimental/dlcheckpoints` and `/home/quinten/.Tribler/7.14/sqlite` to `/home/quinten/.TriblerExperimental/sqlite`.

Please let me know if that doesn't work.

Regarding the search: because search is fully decentralized, there may not be anyone in your neighborhood that can answer your query or there may not be anyone in your neighborhood. We have a debug panel to show how many peers you are connected to, you need to discover peers in the `ContentDiscoveryCommunity` for search to work:

![screenshot](https://github.com/qstokkink/TriblerExperimental/assets/3630389/72613bb2-8710-4854-bbe3-771bb5b76cb9)

**Comment by qstokkink** [comment]
Considering the radio silence for over a month, I assume this question has been sufficiently answered and I will close this issue. Should this not be the case, feel free to respond here or create a new issue.
